compatibility_date = "2023-03-31"
[[d1_databases]]
binding = "DB"
database_name = "learning"
database_id = "01875394-2845-4067-82c1-ffc7db650d38"
preview_database_id = "local-db"
# preview_database_id = "fa1e6524-cd6f-45db-b234-434b7e5a7a71"
